In [209]:
import pandas as pd
import random
import numpy as np
import pandas as pd
import keras
df = pd.read_excel('data/sample_finish.xlsx')
df_id = df['ID1'].tolist()
# random.seed(520)
random_id=random.sample(df_id,1)[0]
random_row=df[df['ID1'] ==random_id]
random_row=eval(random_row['TEXT2_padded'].iloc[0])
df['TEXT1_padded'] = [eval(df['TEXT1_padded'].iloc[i]) for i in range(len(df['TEXT1_padded']))]
df['TEXT2_padded'] = [eval(df['TEXT2_padded'].iloc[i]) for i in range(len(df['TEXT2_padded']))]
test2_row = np.vstack((df['TEXT1_padded'].tolist(),df['TEXT2_padded'].tolist()))
answer_id = df['ID1'].tolist()+df['ID2'].tolist()
random_row = np.array(random_row)
random_row = np.reshape(random_row,(-1,115))
random_row=np.tile(random_row,(test2_row.shape[0],1))
loaded_model = keras.models.load_model("siamese_model.h5")
X1 = keras.preprocessing.sequence.pad_sequences(random_row, padding='post')
X2 = keras.preprocessing.sequence.pad_sequences(test2_row, padding='post')
data1=loaded_model.predict([X1,X2])





125/125 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step


In [206]:
import pandas as pd
import random
import numpy as np
import pandas as pd
import keras
df = pd.read_excel('data/sample_finish.xlsx')
df_id = df['ID1'].tolist()
# random.seed(520)
random_id=random.sample(df_id,1)[0]
random_row=df[df['ID1'] ==random_id]
random_row=eval(random_row['TEXT2_padded'].iloc[0])
df['TEXT1_padded'] = [eval(df['TEXT1_padded'].iloc[i]) for i in range(len(df['TEXT1_padded']))]
df['TEXT2_padded'] = [eval(df['TEXT2_padded'].iloc[i]) for i in range(len(df['TEXT2_padded']))]
test2_row = np.vstack((df['TEXT1_padded'].tolist(),df['TEXT2_padded'].tolist()))
answer_id = df['ID1'].tolist()+df['ID2'].tolist()
random_row = np.array(random_row)
random_row = np.reshape(random_row,(-1,115))
random_row=np.tile(random_row,(test2_row.shape[0],1))
loaded_model = keras.models.load_model("siamese_model.h5")
X1 = keras.preprocessing.sequence.pad_sequences(random_row, padding='post')
X2 = keras.preprocessing.sequence.pad_sequences(test2_row, padding='post')
data2=loaded_model.predict([X1,X2])

125/125 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step


In [207]:
data2

array([[1.1515554e-05],
       [5.1444513e-05],
       [5.3925447e-05],
       ...,
       [5.8774036e-05],
       [3.7375022e-02],
       [1.8414977e-03]], dtype=float32)

In [210]:
max_indices = np.argsort(data1.flatten())[-20:][::-1]
max_values = np.sort(data1.flatten())[-20:][::-1]
max_indices


array([3310,  562, 1287, 3388, 3113, 3402, 3092, 3450, 2499,  176, 3148,
       3966, 2415, 2418,  901, 2103,    6,  697, 1459, 1185], dtype=int64)

In [208]:
max_indices = np.argsort(data2.flatten())[-20:][::-1]
max_values = np.sort(data2.flatten())[-20:][::-1]
max_indices

array([3310, 1287,  562, 3388, 3113, 3092, 3402, 3450, 2499,  176, 3966,
       3148, 2415, 2418,    6,  901,  697, 2103, 1459, 1185], dtype=int64)

In [211]:
answer_id[3310]

28333

In [4]:
import pandas as pd
import numpy as np


tmp_list=[]
label =[]
for i in range(4):
	for j in range(6):
		path='yourpath/'+str(i)+'/pic'+str(j)+'.png'
		print(path)
		tmp_list.append(path)
		label.append(i)


tmp_list=np.array(tmp_list).transpose()
label=np.array(label).transpose()

sample = np.vstack((tmp_list,label)).transpose()

# sample=pd.DataFrame(sample,)


yourpath/0/pic0.png
yourpath/0/pic1.png
yourpath/0/pic2.png
yourpath/0/pic3.png
yourpath/0/pic4.png
yourpath/0/pic5.png
yourpath/1/pic0.png
yourpath/1/pic1.png
yourpath/1/pic2.png
yourpath/1/pic3.png
yourpath/1/pic4.png
yourpath/1/pic5.png
yourpath/2/pic0.png
yourpath/2/pic1.png
yourpath/2/pic2.png
yourpath/2/pic3.png
yourpath/2/pic4.png
yourpath/2/pic5.png
yourpath/3/pic0.png
yourpath/3/pic1.png
yourpath/3/pic2.png
yourpath/3/pic3.png
yourpath/3/pic4.png
yourpath/3/pic5.png


In [7]:
sample

array([['yourpath/0/pic0.png', '0'],
       ['yourpath/0/pic1.png', '0'],
       ['yourpath/0/pic2.png', '0'],
       ['yourpath/0/pic3.png', '0'],
       ['yourpath/0/pic4.png', '0'],
       ['yourpath/0/pic5.png', '0'],
       ['yourpath/1/pic0.png', '1'],
       ['yourpath/1/pic1.png', '1'],
       ['yourpath/1/pic2.png', '1'],
       ['yourpath/1/pic3.png', '1'],
       ['yourpath/1/pic4.png', '1'],
       ['yourpath/1/pic5.png', '1'],
       ['yourpath/2/pic0.png', '2'],
       ['yourpath/2/pic1.png', '2'],
       ['yourpath/2/pic2.png', '2'],
       ['yourpath/2/pic3.png', '2'],
       ['yourpath/2/pic4.png', '2'],
       ['yourpath/2/pic5.png', '2'],
       ['yourpath/3/pic0.png', '3'],
       ['yourpath/3/pic1.png', '3'],
       ['yourpath/3/pic2.png', '3'],
       ['yourpath/3/pic3.png', '3'],
       ['yourpath/3/pic4.png', '3'],
       ['yourpath/3/pic5.png', '3']], dtype='<U19')

In [8]:
import pandas as pd
import numpy as np
import re
import random
def get_num(s):
    text=s
    number = None
    matches = re.findall(r'\d+',text)
    if len(matches) > 0:
        number=int(matches[0])
    return number


df1 = pd.read_csv('data/附件1.csv')
df2 = pd.read_csv('data/附件2.csv')

id_df1= df1['id'].tolist()
id_df2 = df2['questionID'].tolist()
cnt = 0
for i in id_df2:
    if i not in id_df1:
        cnt+=1
print(cnt)
df2_repeat=df2[df2['duplicates'].notnull()]
sep_quesid=df2_repeat['questionID'].tolist()
seq_reid_str=df2_repeat['duplicates'].tolist()
seq_reid=[]
for s in seq_reid_str:
    num=get_num(s)
    seq_reid.append(num)
com_id = np.column_stack((sep_quesid,seq_reid))
for i in sep_quesid:
    id_df1.remove(i)
for i in seq_reid:
    if i in id_df1:
        id_df1.remove(i)
com_id2=[]
for i in range(2000-len(com_id)):
    random.seed(i**3+50+i**2)
    random_numbers = random.sample(id_df1, 2)
    com_id2.append(random_numbers)
com_id2=np.array(com_id2)
com_id_new = np.vstack((com_id,com_id2))
label=[1]*len(com_id)+[0]*len(com_id2)
label= np.array(label)
label=label.reshape(-1,1)
sample = np.hstack((com_id_new,label))
random.seed(521)
indices = np.arange(sample.shape[0])
random.shuffle(indices)
sample=sample[indices]

# 创建一个DataFrame，可以根据需要指定列名
df = pd.DataFrame(sample, columns=['ID1', 'ID2', 'label'])
# df.to_excel('data/sample.xlsx',index=False)



0


In [9]:
sample

array([[ 89938,  35590,      1],
       [ 50415,  25518,      1],
       [ 17537,   7839,      1],
       ...,
       [112580,  44798,      0],
       [ 63022,  62860,      1],
       [ 52975,  48925,      1]])